name: &name "marc2o"
description: "Wonderer. Geek. Human(e) being."
url: "https://marc2o.github.io"
baseurl: ""

atom_feed:
  path: # blank (default) uses feed.xml

mastodon:
  username: &mastodon "@marc2o@mastodon.online"

author:
  name: "Marc Oliver Orth"
  bio: "Wonderer. Geek. Human(e) being."
  location: "Hannover, Germany"

copyright: "&copy; 2021 – 2023 marc2o // Marc Oliver Orth."

highlighter: rouge
encoding: "utf-8"
markdown: "kramdown"

kramdown:
  syntax_highlighter: rouge

# the paginator plugin only works in an index.html!
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-feed

whitelist:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/articles/:num/"

excerpt_separator: <!--more-->

feed:
  excerpt_only: false

defaults: 
  - scope:
      path: "articles"
    values:
      sitemap: false

exclude:
  #- articles
  - google732f743aa7ce0be9.html