name: &name "marc2o"
description: "Wonderer. Geek. Human(e) being."
url: "https://marc2o.github.io"
baseurl: ""

atom_feed:
  path: # blank (default) uses feed.xml

twitter:
  username: &twitter "marc2o"

author:
  name: "Marc Oliver Orth"
  bio: "Wonderer. Geek. Human(e) being."
  location: "Hannover, Germany"

encoding: "utf-8"
markdown: "kramdown"

# the paginator plugin only works in an index.html!
plugins:
  - jekyll-paginate
  - jekyll-sitemap

whitelist:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/articles/:num/"

exclude:
  - articles
  - google732f743aa7ce0be9.html